{{- define "niomon-signer.env" -}}
- name: KAFKA_TOPIC_IN
  value: "ubirch-common-response-json"
- name: KAFKA_TOPIC_OUT
  value: "ubirch-common-rsp-signed-bin"
- name: SIGNER_PRIVATE_KEY_ALGORITHM
  value: "Ed25519"
- name: SIGNER_PRIVATE_KEY
  valueFrom:
    secretKeyRef:
      name: private-keys-niomon
      key: signer-key-ed25519
{{- end -}}

{{- $deployment := (dict "envStr" (include "niomon-signer.env" .)) -}}

{{- $_ := set $deployment "Root" . -}}
{{- $_ := set $deployment "name" "signer" -}}
  {{- $_ := set $deployment "replicas" .Values.signer.replicas -}}

{{ template "niomon.deployment" $deployment }}

---

{{ template "niomon.service" $deployment }}

---

{{ template "niomon.prometheus.monitor" $deployment}}
